//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc21622test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemployee
    {
        //tblemployee :-modeL
        public int empid { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> country { get; set; }
        public Nullable<int> state { get; set; }
    }
}
