//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc21622test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblgender
    {
        public int gid { get; set; }
        public string gname { get; set; }
    }
}
